### ISSUE TITLE
Please add support for recent versions of errors

### ISSUE THREAD

**Issue by peti** [stackbuilders/octohat#33]
After updating NixOS to errors 2.x, we can no longer built your package: http://packdeps.haskellers.com/feed?needle=octohat.

**Comment by jsantos17** [comment]
I'll see what I can do. Thanks for letting me know it doesn't work with
newer versions!

**Comment by juanpaucar** [comment]
@jsantos17 It seems that the types these functions have changed from `EitherT e m a` to `ExceptT e m a` in the change from errors [1.4.7](https://hackage.haskell.org/package/errors-1.4.7) to [2.0.0](https://hackage.haskell.org/package/errors-2.0.0)
- `tryRight`
- `tryAssert`
- `tryHead`

So it's no just updating the package

**Comment by jsl** [comment]
I wonder if there is an errors-compat shim, or how hard it would be to make
one. Since it seems likely that upstream packages may depend on either
version this could be useful.

On Sunday, August 16, 2015, Juan Paucar <notifications@github.com> wrote:

> @jsantos17 <https://github.com/jsantos17> It seems that the types these
> functions have changed from EitherT e m a to ExceptT e m a in the change
> from errors 1.4.7 <https://hackage.haskell.org/package/errors-1.4.7> to
> 2.0.0 <https://hackage.haskell.org/package/errors-2.0.0>
>
>    - tryRight
>    - tryAssert
>    - tryHead
>
> So it's no just updating the package
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stackbuilders/octohat/issues/33#issuecomment-131577719>
> .
>


-- 
Justin Leitgeb <http://justinleitgeb.com>
Twitter: @justinleitgeb <http://twitter.com/justinleitgeb>
Github: @jsl <https://github.com/jsl>

Co-Founder and CTO, Stack Builders Inc. <http://www.stackbuilders.com>

**Comment by jsantos17** [comment]
@jsl @juanpaucar  updating is trivial with a bit of ugly, CPP magic. @juanpaucar is already on it. We could definitely move that out into a different package so we can depend on that instead. That way we can contain the CPP there. Another option is finding some sort typeclass constraint that works for both and make `GitHub` polymorphic enough to support both.

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by jsantos17** [comment]
Yes, within a few hours.

**Comment by juanpaucar** [comment]
@peti it's on hackage now http://hackage.haskell.org/package/octohat-0.1.5.0
